# Generated by Django 3.0.7 on 2021-04-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('project_detail', models.CharField(max_length=50, verbose_name='项目描述')),
                ('project_manager', models.CharField(max_length=50, verbose_name='项目负责人')),
                ('project_status', models.CharField(choices=[('1', '正在进行'), ('0', '取消'), ('2', '已完成')], default='1', max_length=20, verbose_name='状态')),
                ('project_process', models.CharField(default=0, max_length=3, verbose_name='项目进度')),
                ('project_company', models.CharField(max_length=20, verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'ProjectInfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='邮箱名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_name', models.CharField(max_length=20, verbose_name='用例名称')),
                ('case_detail', models.CharField(max_length=50, verbose_name='用例描述')),
                ('case_level', models.CharField(choices=[('0', 'P0'), ('1', 'P1'), ('2', 'P2')], default='1', max_length=20, verbose_name='用例级别')),
                ('case_status', models.CharField(choices=[('1', '成功'), ('0', '失败'), ('2', '未运行')], default='1', max_length=20, verbose_name='状态')),
                ('case_type', models.CharField(choices=[('0', '功能'), ('1', '性能'), ('2', '安全'), ('3', '稳定')], default=0, max_length=20, verbose_name='用例类型')),
                ('belong_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPlatform.ProjectInfo')),
            ],
            options={
                'verbose_name': '用例信息',
                'db_table': 'TestCaseInfo',
            },
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('member', models.CharField(max_length=50, verbose_name='项目成员')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPlatform.ProjectInfo')),
            ],
            options={
                'verbose_name': '图片地址',
                'db_table': 'PictureInfo',
            },
        ),
        migrations.CreateModel(
            name='InterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inter_url', models.CharField(max_length=100, verbose_name='接口url')),
                ('inter_method', models.CharField(max_length=5, verbose_name='接口类型')),
                ('inter_headers', models.TextField(max_length=200, verbose_name='接口头信息')),
                ('inter_params', models.TextField(max_length=200, verbose_name='接口参数')),
                ('belong_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPlatform.TestCaseInfo')),
            ],
            options={
                'verbose_name': '接口信息',
                'db_table': 'InterInfo',
            },
        ),
    ]
