# Generated by Django 3.0.7 on 2021-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='邮箱名'),
        ),
    ]
